### ISSUE TITLE
python 3.7 is supported, but package is using python 3.8 features 

### ISSUE THREAD

**Issue by shannonchoang** [hex-inc/airflow-provider-hex#10]
Hello, 
I had previously opened an issue asking for python 3.7 support. While this was accommodated, there are lines of code in the repo that do not work in python 3.7 as they are features of 3.8. 

Ie. TypedDict was introduced in Python 3.8
https://github.com/python/typeshed/issues/3500 but is used in types.py 

Ie in the __init_.py file import importlib.metadata is used but this was not supported until 3.8.

**Comment by PedramNavid** [comment]
Closed by #11
