### ISSUE TITLE
Missing 0.1.6 Release on PyPi

### ISSUE THREAD

**Issue by DobsX** [hex-inc/airflow-provider-hex#5]
First, thank-you for releasing this Airflow provider/operators for Hex!

FYI, I noticed that the `0.1.6` is [not on PyPi](https://pypi.org/project/airflow-provider-hex/#history).  Latest version is `0.1.5`.  Any chance we can publish `0.1.6`?

**Comment by PedramNavid** [comment]
Hi @DobsX just released, looks like I missed a failure in the CI workflow. I tried turning it off and on again, and that fixed it so you should see 0.1.6 on pypi now!

https://pypi.org/project/airflow-provider-hex/0.1.6/
