### ISSUE TITLE
previous versions 

### ISSUE THREAD

**Issue by shannonchoang** [hex-inc/airflow-provider-hex#7]
Hi, 
Are previous versions of this package available? I am working with python 3.7 so am unable to use the latest distribution.
Attempts to install previous versions fails 
pip install airflow-provider-hex==0.1.5
ERROR: Could not find a version that satisfies the requirement airflow-provider-hex==0.1.5 (from versions: none)
ERROR: No matching distribution found for airflow-provider-hex==0.1.5

**Comment by PedramNavid** [comment]
Hi @shannonchoang, sure can! Just updated the requirements and tested it in #8.
Release 0.1.7 should be out soon with support for 3.7.

You can run this to upgrade once the build is complete. 
```
pip install airflow-provider-hex>=0.1.7
```
